version: '3'
services:
  #prod:
    #build: ./docker/production
    #ports:
      #- "3092:9292" # rails (psql)
    #tty: true
    #stdin_open: true
    #networks:
      #- proxy-net
  test_service:
    build: test_service
    environment:
      #- "DATABASE_PASSWORD=password"
      #- "COMMON_HOST=db-postgresql"
      #- "COMMON_USERNAME=rails"
      #- "COMMON_PASSWORD=password"
      - "PAGER='busybox more'"
      - "SSH_AUTH_SOCK=/tmp/ssh-agent"
    tty: true
    stdin_open: true
    volumes:
      - "$PWD/test_service:/var/www/test_service:Z"
      - $SSH_AUTH_SOCK:/tmp/ssh-agent:Z
    ports:
      - "3037:3000" # rails (psql)
    networks:
      - proxy-net
      
networks:
  proxy-net:
    external:
      name: common_network
