version: "3"
services:
  geocoder_microservice_app:
    extends:
      file: ../composer-files/docker-compose.common_services.yml
      service: app
    ports:
      - "127.0.0.1:4030:5000"
    env_file:
      - ../auth_microservice/.env
    volumes:
      - ../geocoder_microservice/:/apps/geocoder_microservice/
    working_dir: /apps/geocoder_microservice